controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#post_api:
#    resource: '../src/Controller/PostController.php'
#    type: annotation